import React, {FC} from 'react';
import Header from "./Header";
import Head from "next/head";

interface MainLayoutProps {
    title: string,
    children: React.ReactNode
}

const MainLayout: FC<MainLayoutProps> = ({title = "Любо знать", children}) => {
    return (
        <div className={"h-screen font-sans"}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main className={"h-full pt-24 md:pt-28 lg:pt-32"}>
                <div className={"container mx-auto "}>
                    {children}
                </div>
            </main>
        </div>
    );
};

export default MainLayout;